### ISSUE TITLE
请问为什么visdrone的make_json中只有9类？

### ISSUE THREAD

**Issue by Disciple7** [ChenhongyiYang/QueryDet-PyTorch#57]
作者是否把pedestrian的标记去掉了？还有ignore_region和others的label是怎么处理和计算的？

**Comment by ChenhongyiYang** [comment]
Hi, we are sorry it was a bug. We incorrectly update the bug version of the data-converting script. It has been fixed for now.  In fact, we did meet this bug when we were testing QueryDet on Visdrone, but found it rarely affects the mAP. The reason was that the performance for the last category "motor" was very bad, i.e., adding it as a valid category did not really help because its AP was very small. 

For "ignore" and "others", we simply removed them from the annotation without any particular processing.

Hope this reply can solve your problem.
